package repository

import (
	"database/sql"
	"log"

	_ "github.com/lib/pq"
)

//create tables
func CreateDB() (*sql.DB, error) {
	// configDb := "postgres://user:password@localhost:5432/userdb?sslmode=disable"
	configDb := "user=postgres dbname=usersdb sslmode=disable"
	db, err := sql.Open("postgres", configDb)
	if err != nil {
		log.Println(err, 1)

		return nil, err
	}
	if err = db.Ping(); err != nil {
		return nil, err
	}

	users, err := db.Prepare(`CREATE TABLE users (
		id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		uuid varchar(255) NOT NULL,
		firstname varchar(255) NOT NULL,
		lastname varchar(255) NOT NULL,
		email varchar(255) NOT NULL UNIQUE,
		age number NOT NULL,
		createdtime timestamp
	)`)
	if err != nil {
		return nil, err
	}
	users.Exec()
	return db, nil
}
