package repository

import (
	"database/sql"

	_ "github.com/lib/pq"
)

//create tables
func CreateDB() (*sql.DB, error) {
	configDb := "postgres://postgres:postgres@localhost:5432/userdb?sslmode=disable"
	db, err := sql.Open("postgres", configDb)
	if err != nil {
		return nil, err
	}
	if err = db.Ping(); err != nil {
		return nil, err
	}

	// defer db.Close()

	users, err := db.Prepare(`CREATE TABLE IF NOT EXISTS users  (
		id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		uuid varchar(255) NOT NULL,
		firstname varchar(255) NOT NULL,
		lastname varchar(255) NOT NULL,
		email varchar(255) NOT NULL UNIQUE,
		age int NOT NULL,
		createdtime timestamp
	)`)
	if err != nil {
		return nil, err
	}
	users.Exec()
	return db, nil
}
